"use client";
/* eslint-disable react/no-unescaped-entities, react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { onboardingLabels, type OnboardingProject } from "@/lib/onboarding";
import type { ProductionCompleteness, ProductionDossier, ProductionMedia } from "@/lib/production";

type AccessRow = { category: string; status: string; client_choice: string | null; client_note: string | null };
type Service = { title: string; description: string };
type FormState = {
  currentStep: number; publicName: string; businessDescription: string; publicAddress: string; addressPublic: boolean; publicCity: string; serviceAreas: string[]; publicPhone: string; publicEmail: string; openingHours: Record<string, string>; socialUrls: string[];
  services: Service[]; requestedPages: string[]; priorityServices: string[]; differentiators: string[]; primaryCta: string; requestedFeatures: string[]; contentPreferences: Record<string, unknown>;
  seoPrimaryActivity: string; seoPriorityServices: string[]; seoPrimaryCity: string; seoSecondaryAreas: string[]; seoAudience: string; seoReferenceUrls: string[];
  legalName: string; legalForm: string; sirenSiret: string; legalAddress: string; technicalDomain: string; technicalRegistrar: string; technicalHost: string; technicalCms: string; technicalAccess: Record<string, string>; rightsConfirmed: boolean; clientConfirmation: boolean;
};

const featureOptions = [["contact", "Formulaire de contact"], ["devis", "Demande de devis"], ["rendez_vous", "Prise de rendez-vous"], ["galerie", "Galerie"], ["avis", "Retours clients"], ["faq", "FAQ"], ["tarifs", "Tarifs"], ["carte", "Carte / localisation"], ["catalogue", "Catalogue"], ["horaires", "Horaires"], ["telephone", "Bouton téléphone"], ["whatsapp", "Bouton WhatsApp"], ["aucune", "Aucune fonctionnalité spécifique"]] as const;
const differentiatorOptions = ["Expérience", "Rapidité", "Proximité", "Spécialisation", "Garantie", "Disponibilité", "Accompagnement", "Autre"];
const ctaOptions = [["devis", "Demander un devis"], ["appel", "Appeler"], ["rendez_vous", "Prendre rendez-vous"], ["message", "Envoyer un message"], ["visite", "Venir dans l'établissement"]];
const accessOptions = [["connait_acces", "Je l'ai"], ["partiel", "Je l'ai partiellement"], ["ne_sait_pas", "Je ne sais pas"], ["agence", "Mon prestataire le gère"], ["non_necessaire", "Non nécessaire"]];
const stepTitles = ["Votre entreprise", "Vos services", "Votre site", "Vos contenus", "Vos éléments", "Votre référencement", "Dernières informations"];
const emptyState = (project: OnboardingProject): FormState => ({
  currentStep: 1, publicName: project.company ?? "", businessDescription: "", publicAddress: "", addressPublic: true, publicCity: "", serviceAreas: [], publicPhone: project.phone ?? "", publicEmail: project.email ?? "", openingHours: {}, socialUrls: [], services: [], requestedPages: project.requestedPages, priorityServices: [], differentiators: [], primaryCta: "", requestedFeatures: [], contentPreferences: {}, seoPrimaryActivity: "", seoPriorityServices: [], seoPrimaryCity: "", seoSecondaryAreas: [], seoAudience: "", seoReferenceUrls: [], legalName: "", legalForm: "", sirenSiret: "", legalAddress: "", technicalDomain: project.existingSiteUrl ?? "", technicalRegistrar: "", technicalHost: "", technicalCms: "", technicalAccess: {}, rightsConfirmed: false, clientConfirmation: false,
});

function toState(project: OnboardingProject, dossier: ProductionDossier | null): FormState {
  const base = emptyState(project);
  if (!dossier) return base;
  return { ...base, currentStep: dossier.current_step, publicName: dossier.public_name ?? base.publicName, businessDescription: dossier.business_description ?? "", publicAddress: dossier.public_address ?? "", addressPublic: dossier.address_public, publicCity: dossier.public_city ?? "", serviceAreas: dossier.service_areas, publicPhone: dossier.public_phone ?? base.publicPhone, publicEmail: dossier.public_email ?? base.publicEmail, openingHours: dossier.opening_hours, socialUrls: dossier.social_urls, services: dossier.services.map((service) => ({ title: service.title, description: service.description ?? "" })), requestedPages: dossier.requested_pages.length ? dossier.requested_pages : base.requestedPages, priorityServices: dossier.priority_services, differentiators: dossier.differentiators, primaryCta: dossier.primary_cta ?? "", requestedFeatures: dossier.requested_features, contentPreferences: dossier.content_preferences, seoPrimaryActivity: dossier.seo_primary_activity ?? "", seoPriorityServices: dossier.seo_priority_services, seoPrimaryCity: dossier.seo_primary_city ?? "", seoSecondaryAreas: dossier.seo_secondary_areas, seoAudience: dossier.seo_audience ?? "", seoReferenceUrls: dossier.seo_reference_urls, legalName: dossier.legal_name ?? "", legalForm: dossier.legal_form ?? "", sirenSiret: dossier.siren_siret ?? "", legalAddress: dossier.legal_address ?? "", technicalDomain: dossier.technical_domain ?? base.technicalDomain, technicalRegistrar: dossier.technical_registrar ?? "", technicalHost: dossier.technical_host ?? "", technicalCms: dossier.technical_cms ?? "", technicalAccess: dossier.technical_access, rightsConfirmed: dossier.rights_confirmed, clientConfirmation: dossier.client_confirmation };
}

function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) { return <label className="production-field"><span>{label}</span>{children}{hint && <small>{hint}</small>}</label>; }
function CheckList({ options, values, onChange }: { options: readonly (readonly [string, string])[]; values: string[]; onChange: (value: string) => void }) { return <div className="production-choice-grid">{options.map(([value, text]) => <label className={`production-choice ${values.includes(value) ? "selected" : ""}`} key={value}><input type="checkbox" checked={values.includes(value)} onChange={() => onChange(value)} />{text}</label>)}</div>; }
function addItem(items: string[], value: string) { const trimmed = value.trim(); return trimmed && !items.includes(trimmed) ? [...items, trimmed] : items; }

export function ProductionDossierForm({ project }: { project: OnboardingProject }) {
  const [state, setState] = useState<FormState>(() => emptyState(project));
  const [, setDossier] = useState<ProductionDossier | null>(null);
  const [media, setMedia] = useState<ProductionMedia[]>([]);
  const [access, setAccess] = useState<AccessRow[]>([]);
  const [completeness, setCompleteness] = useState<ProductionCompleteness | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [newArea, setNewArea] = useState("");
  const [newSocial, setNewSocial] = useState("");
  const [newSeoArea, setNewSeoArea] = useState("");
  const [newReference, setNewReference] = useState("");
  const [fileType, setFileType] = useState("photo");

  const refresh = async () => {
    const response = await fetch("/api/client/production", { cache: "no-store" });
    if (!response.ok) throw new Error("Dossier indisponible.");
    const data = await response.json() as { dossier: ProductionDossier | null; access: AccessRow[]; media: ProductionMedia[]; completeness: ProductionCompleteness };
    setDossier(data.dossier); setState(toState(project, data.dossier)); setAccess(data.access); setMedia(data.media); setCompleteness(data.completeness);
  };
  useEffect(() => { void refresh().catch((reason) => setError(reason instanceof Error ? reason.message : "Dossier indisponible.")).finally(() => setLoading(false)); }, []);

  const update = <K extends keyof FormState>(key: K, value: FormState[K]) => setState((current) => ({ ...current, [key]: value }));
  const toggle = (key: "differentiators" | "requestedFeatures" | "seoPriorityServices", value: string) => update(key, state[key].includes(value) ? state[key].filter((item) => item !== value) : [...state[key], value]);
  const togglePriority = (value: string) => update("priorityServices", state.priorityServices.includes(value) ? state.priorityServices.filter((item) => item !== value) : state.priorityServices.length < 3 ? [...state.priorityServices, value] : state.priorityServices);
  const save = async (nextStep: number, completed = false) => {
    setSaving(true); setError(""); setMessage("");
    const response = await fetch("/api/client/production", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...state, currentStep: nextStep, completed, clientConfirmation: completed ? true : state.clientConfirmation }) });
    const data = await response.json().catch(() => ({})) as { error?: string; completeness?: ProductionCompleteness; dossier?: ProductionDossier };
    setSaving(false);
    if (!response.ok) { setError(data.error ?? "Impossible d'enregistrer le dossier."); if (data.completeness) setCompleteness(data.completeness); return false; }
    if (data.dossier) setDossier(data.dossier); if (data.completeness) setCompleteness(data.completeness); setState((current) => ({ ...current, currentStep: nextStep, clientConfirmation: completed ? true : current.clientConfirmation })); setMessage("Enregistré"); return true;
  };
  const setAccessChoice = async (category: string, choice: string) => {
    setError(""); const response = await fetch("/api/client/production/access", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ category, clientChoice: choice }) });
    if (!response.ok) { setError("Impossible d'enregistrer ce choix d'accès."); return; }
    setAccess((items) => [...items.filter((item) => item.category !== category), { category, status: choice === "non_necessaire" ? "non_necessaire" : "a_fournir", client_choice: choice === "non_necessaire" ? null : choice, client_note: null }]);
  };
  const upload = async (file: File) => {
    const body = new FormData(); body.set("file", file); body.set("mediaType", fileType); setError("");
    const response = await fetch("/api/client/production/media", { method: "POST", body }); const data = await response.json().catch(() => ({})) as { error?: string; media?: ProductionMedia };
    if (!response.ok) { setError(data.error ?? "Impossible d'ajouter ce fichier."); return; }
    if (data.media) setMedia((items) => [data.media!, ...items]);
  };
  const removeMedia = async (id: string) => { const response = await fetch("/api/client/production/media", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id }) }); if (response.ok) setMedia((items) => items.filter((item) => item.id !== id)); };
  const step = state.currentStep;
  const displayArea = (key: "serviceAreas" | "seoSecondaryAreas" | "socialUrls" | "seoReferenceUrls", value: string, setValue: (value: string) => void) => <div className="production-inline-add"><input value={value} onChange={(event) => setValue(event.target.value)} placeholder="Ajouter une ville ou zone" /><button type="button" className="client-button secondary" onClick={() => { update(key, addItem(state[key], value)); setValue(""); }}>Ajouter</button></div>;
  const saveAndNext = async () => { if (step < 7) await save(step + 1); else await save(7, true); };
  const hasExistingSite = project.hasExistingSite;
  const source = typeof state.contentPreferences.presentationSource === "string" ? state.contentPreferences.presentationSource : "";
  const setContent = (key: string, value: unknown) => update("contentPreferences", { ...state.contentPreferences, [key]: value });
  const selectedAccess = (category: string) => access.find((item) => item.category === category)?.client_choice ?? (access.find((item) => item.category === category)?.status === "non_necessaire" ? "non_necessaire" : "");
  const progress = completeness?.score ?? 0;
  const activeTitle = stepTitles[step - 1];
  const summary = useMemo(() => `${state.services.length} service${state.services.length > 1 ? "s" : ""} · ${project.requestedPages.length} page${project.requestedPages.length > 1 ? "s" : ""} commerciale${project.requestedPages.length > 1 ? "s" : ""}`, [state.services.length, project.requestedPages.length]);

  if (loading) return <section className="production-shell"><p className="client-muted-note">Chargement de votre dossier…</p></section>;
  return <section className="production-shell">
    <div className="production-header"><div><p className="client-eyebrow">DOSSIER DE PRODUCTION</p><h2>Préparons votre site</h2><p>Quelques informations structurées permettront à FeaseWeb de commencer la création sans vous redemander l'essentiel.</p></div><div className="production-progress"><strong>{progress} %</strong><span>Dossier de production</span><div><i style={{ width: `${progress}%` }} /></div></div></div>
    <ol className="production-steps" aria-label="Étapes du dossier de production">{stepTitles.map((title, index) => <li className={index + 1 === step ? "active" : index + 1 < step ? "complete" : ""} key={title}><span>{index + 1 < step ? "✓" : index + 1}</span><small>{title}</small></li>)}</ol>
    <div className="production-form-head"><div><p className="client-eyebrow">ÉTAPE {step} SUR 7</p><h3>{activeTitle}</h3></div><p>{summary}</p></div>
    {error && <p className="production-message error" role="alert">{error}</p>}{message && <p className="production-message" role="status">{message}</p>}
    <div className="production-form-card">
      {step === 1 && <div className="production-form-grid"><Field label="Nom public"><input value={state.publicName} onChange={(event) => update("publicName", event.target.value)} /></Field><Field label="Description courte" hint="Expliquez simplement ce que fait votre entreprise."><textarea value={state.businessDescription} onChange={(event) => update("businessDescription", event.target.value)} rows={4} /></Field><Field label="Adresse publique"><input value={state.publicAddress} onChange={(event) => update("publicAddress", event.target.value)} disabled={!state.addressPublic} placeholder="Adresse, rue et code postal" /></Field><label className="production-check"><input type="checkbox" checked={!state.addressPublic} onChange={(event) => update("addressPublic", !event.target.checked)} /> Je ne souhaite pas afficher mon adresse</label><Field label="Ville"><input value={state.publicCity} onChange={(event) => update("publicCity", event.target.value)} /></Field><Field label="Téléphone public"><input value={state.publicPhone} onChange={(event) => update("publicPhone", event.target.value)} /></Field><Field label="Email public"><input type="email" value={state.publicEmail} onChange={(event) => update("publicEmail", event.target.value)} /></Field><Field label="Zones d'intervention">{displayArea("serviceAreas", newArea, setNewArea)}<div className="production-tags">{state.serviceAreas.map((item) => <button type="button" key={item} onClick={() => update("serviceAreas", state.serviceAreas.filter((area) => area !== item))}>{item} ×</button>)}</div></Field><Field label="Horaires" hint="Choisissez une base, puis précisez si nécessaire."><select value={state.openingHours.mode ?? ""} onChange={(event) => update("openingHours", { ...state.openingHours, mode: event.target.value })}><option value="">À préciser</option><option value="semaine">Du lundi au vendredi</option><option value="semaine_samedi">Du lundi au samedi</option><option value="sur_rendez_vous">Sur rendez-vous</option><option value="personnalises">Horaires personnalisés</option></select></Field><Field label="Réseaux sociaux" hint="URLs uniquement.">{displayArea("socialUrls", newSocial, setNewSocial)}<div className="production-tags">{state.socialUrls.map((item) => <button type="button" key={item} onClick={() => update("socialUrls", state.socialUrls.filter((url) => url !== item))}>{item} ×</button>)}</div></Field></div>}
      {step === 2 && <div className="production-form-grid"><div className="production-wide"><p className="production-label">Prestations</p>{state.services.map((service, index) => <div className="production-service-row" key={`${service.title}-${index}`}><input placeholder="Intitulé de la prestation" value={service.title} onChange={(event) => update("services", state.services.map((item, itemIndex) => itemIndex === index ? { ...item, title: event.target.value } : item))} /><input placeholder="Courte description (facultative)" value={service.description} onChange={(event) => update("services", state.services.map((item, itemIndex) => itemIndex === index ? { ...item, description: event.target.value } : item))} /><button type="button" onClick={() => update("services", state.services.filter((_, itemIndex) => itemIndex !== index))}>Supprimer</button></div>)}<button type="button" className="client-button secondary" onClick={() => update("services", [...state.services, { title: "", description: "" }])}>Ajouter une prestation</button></div><div className="production-wide"><p className="production-label">Prestations prioritaires <small>(maximum 3)</small></p><CheckList options={state.services.filter((service) => service.title.trim()).map((service) => [service.title, service.title] as const)} values={state.priorityServices} onChange={togglePriority} /></div><div className="production-wide"><p className="production-label">Ce qui vous différencie</p><CheckList options={differentiatorOptions.map((item) => [item, item] as const)} values={state.differentiators} onChange={(value) => toggle("differentiators", value)} /></div><div className="production-wide"><p className="production-label">Action principale</p><div className="production-choice-grid">{ctaOptions.map(([value, text]) => <label className={`production-choice ${state.primaryCta === value ? "selected" : ""}`} key={value}><input type="radio" name="primary-cta" checked={state.primaryCta === value} onChange={() => update("primaryCta", value)} />{text}</label>)}</div></div></div>}
      {step === 3 && <div className="production-form-grid"><div className="production-wide"><p className="production-label">Pages à produire</p><CheckList options={project.requestedPages.map((page) => [page, onboardingLabels[page] ?? page] as const)} values={state.requestedPages} onChange={(value) => update("requestedPages", state.requestedPages.includes(value) ? state.requestedPages.filter((item) => item !== value) : [...state.requestedPages, value])} /><p className="production-help">Vous pouvez confirmer ou ajuster les pages choisies dans la configuration commerciale.</p></div><div className="production-wide"><p className="production-label">Fonctionnalités demandées</p><CheckList options={featureOptions} values={state.requestedFeatures} onChange={(value) => update("requestedFeatures", value === "aucune" ? ["aucune"] : state.requestedFeatures.filter((item) => item !== "aucune").includes(value) ? state.requestedFeatures.filter((item) => item !== value) : [...state.requestedFeatures.filter((item) => item !== "aucune"), value])} /></div><Field label="Objectif principal"><input value={project.primaryObjective ?? ""} readOnly /></Field><Field label="Création / refonte"><input value={hasExistingSite ? "Refonte du site existant" : "Création d'un nouveau site"} readOnly /></Field></div>}
      {step === 4 && <div className="production-form-grid"><div className="production-wide"><p className="production-label">Présentation</p><div className="production-choice-grid"><label className={`production-choice ${source === "client_text" ? "selected" : ""}`}><input type="radio" checked={source === "client_text"} onChange={() => setContent("presentationSource", "client_text")} />J'ai déjà un texte</label><label className={`production-choice ${source === "feaseweb" ? "selected" : ""}`}><input type="radio" checked={source === "feaseweb"} onChange={() => setContent("presentationSource", "feaseweb")} />FeaseWeb peut le structurer/rédiger à partir de mes informations</label></div></div><div className="production-wide"><p className="production-label">Vos contenus</p>{[["servicesText", "J'ai des textes pour mes prestations"], ["reviews", "Je dispose de retours clients"], ["realisations", "Je dispose de réalisations"], ["certifications", "Je dispose de certifications ou labels"], ["faq", "Je dispose d'une FAQ"]].map(([key, text]) => <label className="production-check" key={key}><input type="checkbox" checked={state.contentPreferences[key] === true} onChange={(event) => setContent(key, event.target.checked)} />{text}</label>)}</div><Field label="Précision utile" hint="Ajoutez uniquement une information indispensable à la préparation."><textarea value={typeof state.contentPreferences.note === "string" ? state.contentPreferences.note : ""} onChange={(event) => setContent("note", event.target.value)} rows={4} placeholder="Facultatif" /></Field></div>}
      {step === 5 && <div className="production-form-grid"><div className="production-wide"><p className="production-label">Ajouter un fichier</p><div className="production-upload-line"><select value={fileType} onChange={(event) => setFileType(event.target.value)}>{[["logo", "Logo"], ["photo", "Photo"], ["realisation", "Réalisation"], ["avis_document", "Avis / document"], ["certification", "Certification"], ["document_utile", "Document utile"]].map(([value, text]) => <option value={value} key={value}>{text}</option>)}</select><input type="file" accept="image/jpeg,image/png,image/webp,image/gif,application/pdf" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); event.currentTarget.value = ""; }} /></div><p className="production-help">Images usuelles ou PDF, 10 Mo maximum par fichier. Les éléments restent privés et ne sont accessibles qu'à vous et à FeaseWeb.</p></div><div className="production-wide"><p className="production-label">Éléments transmis</p>{media.length ? <ul className="production-media-list">{media.map((item) => <li key={item.id}><span>{item.original_name}</span><small>{item.media_type} · {Math.round(item.size_bytes / 1024)} Ko</small><button type="button" onClick={() => void removeMedia(item.id)}>Supprimer</button></li>)}</ul> : <p className="client-muted-note">Aucun fichier ajouté pour le moment.</p>}</div><label className="production-check production-wide"><input type="checkbox" checked={state.rightsConfirmed} onChange={(event) => update("rightsConfirmed", event.target.checked)} /> Je confirme disposer des droits nécessaires pour transmettre ces éléments à FeaseWeb afin de préparer mon site.</label></div>}
      {step === 6 && <div className="production-form-grid"><Field label="Métier / activité principale"><input value={state.seoPrimaryActivity} onChange={(event) => update("seoPrimaryActivity", event.target.value)} placeholder="Ex. plombier chauffagiste" /></Field><Field label="Ville principale"><input value={state.seoPrimaryCity} onChange={(event) => update("seoPrimaryCity", event.target.value)} /></Field><Field label="Services prioritaires" hint="Choisissez jusqu'à trois prestations déjà ajoutées."><CheckList options={state.services.slice(0, 3).map((service) => [service.title, service.title] as const)} values={state.seoPriorityServices} onChange={(value) => toggle("seoPriorityServices", value)} /></Field><Field label="Zones secondaires">{displayArea("seoSecondaryAreas", newSeoArea, setNewSeoArea)}<div className="production-tags">{state.seoSecondaryAreas.map((item) => <button type="button" key={item} onClick={() => update("seoSecondaryAreas", state.seoSecondaryAreas.filter((area) => area !== item))}>{item} ×</button>)}</div></Field><Field label="Clientèle recherchée" hint="Facultatif"><input value={state.seoAudience} onChange={(event) => update("seoAudience", event.target.value)} /></Field><Field label="Sites de référence ou concurrents" hint="URLs uniquement, facultatif.">{displayArea("seoReferenceUrls", newReference, setNewReference)}<div className="production-tags">{state.seoReferenceUrls.map((item) => <button type="button" key={item} onClick={() => update("seoReferenceUrls", state.seoReferenceUrls.filter((url) => url !== item))}>{item} ×</button>)}</div></Field></div>}
      {step === 7 && <div className="production-form-grid"><div className="production-wide"><p className="production-label">Informations légales</p><div className="production-form-grid nested"><Field label="Nom légal / raison sociale"><input value={state.legalName} onChange={(event) => update("legalName", event.target.value)} /></Field><Field label="Forme juridique"><input value={state.legalForm} onChange={(event) => update("legalForm", event.target.value)} placeholder="Ex. EI, SASU, SARL" /></Field><Field label="SIREN / SIRET"><input value={state.sirenSiret} onChange={(event) => update("sirenSiret", event.target.value)} /></Field><Field label="Adresse légale"><input value={state.legalAddress} onChange={(event) => update("legalAddress", event.target.value)} /></Field></div></div>{hasExistingSite && <div className="production-wide"><p className="production-label">Refonte et accès</p><p className="production-help">Un registrar est l'entreprise chez qui votre nom de domaine a été acheté. Ne transmettez jamais de mot de passe, clé API ou token ici.</p><div className="production-form-grid nested"><Field label="Domaine actuel"><input value={state.technicalDomain} onChange={(event) => update("technicalDomain", event.target.value)} /></Field><Field label="Registrar connu"><input value={state.technicalRegistrar} onChange={(event) => update("technicalRegistrar", event.target.value)} /></Field><Field label="Hébergeur connu"><input value={state.technicalHost} onChange={(event) => update("technicalHost", event.target.value)} /></Field><Field label="CMS connu"><input value={state.technicalCms} onChange={(event) => update("technicalCms", event.target.value)} /></Field></div><div className="production-access-grid">{[["domaine", "Domaine"], ["dns", "DNS"], ["hebergement", "Hébergement"], ["cms", "CMS"]].map(([category, label]) => <label className="production-field" key={category}><span>{label}</span><select value={selectedAccess(category)} onChange={(event) => void setAccessChoice(category, event.target.value)}><option value="">Choisir</option>{accessOptions.map(([value, text]) => <option value={value} key={value}>{text}</option>)}</select></label>)}</div></div>}<div className="production-wide production-final-confirmation"><p>Récapitulatif</p><p className="production-help">Votre configuration commerciale, vos pages, votre style et votre palette sont déjà repris par FeaseWeb. En confirmant, vous autorisez FeaseWeb à utiliser les informations fournies pour préparer votre site.</p><label className="production-check"><input type="checkbox" checked={state.clientConfirmation} onChange={(event) => update("clientConfirmation", event.target.checked)} /> Les informations fournies peuvent être utilisées par FeaseWeb pour préparer mon site.</label></div></div>}
    </div>
    <div className="production-actions"><button type="button" className="client-button secondary" disabled={saving || step === 1} onClick={() => void save(Math.max(1, step - 1))}>Précédent</button><span>{saving ? "Enregistrement…" : message}</span><button type="button" className="client-button" disabled={saving || (step === 7 && !state.clientConfirmation)} onClick={() => void saveAndNext()}>{step === 7 ? "Confirmer mon dossier" : "Enregistrer et continuer"}</button></div>
  </section>;
}
