-- FeaseWeb V4 schema entry point.
--
-- The executable, versioned PostgreSQL schema now lives in:
--   supabase/migrations/20260922140000_backoffice_v4.sql
--
-- Apply it with the Supabase CLI migration workflow. This file remains as a
-- discoverable pointer for the existing documentation and should not be
-- edited independently of the migration.
