import type { BackofficeData, ActivityLog, Client, ClientUpdate, Domain, ModificationRequest, Payment, Prospect, SeoAction, SeoMetric, Site, Subscription } from "@/lib/backoffice";

type Row = Record<string, unknown>;
const stringValue = (row: Row, key: string) => typeof row[key] === "string" ? row[key] as string : "";
const booleanValue = (row: Row, key: string) => row[key] === true;
const notesFor = (rows: Row[], key: string, id: string) => rows.filter((row) => row[key] === id).map((row) => stringValue(row, "body"));

export function mapBackofficeRows(rows: Record<string, Row[]>) : BackofficeData {
  const prospects: Prospect[] = (rows.prospects ?? []).map((row) => ({ id: stringValue(row, "id"), createdAt: stringValue(row, "created_at"), firstName: stringValue(row, "first_name"), lastName: stringValue(row, "last_name"), company: stringValue(row, "company"), email: stringValue(row, "email"), phone: stringValue(row, "phone"), activity: stringValue(row, "activity"), city: stringValue(row, "city"), currentSite: stringValue(row, "existing_site_url"), hasSite: booleanValue(row, "has_existing_site"), objective: stringValue(row, "objective"), message: stringValue(row, "message"), source: stringValue(row, "source"), status: row.status as Prospect["status"], notes: notesFor(rows.internalNotes ?? [], "prospect_id", stringValue(row, "id")) }));
  let clients: Client[] = (rows.clients ?? []).map((row) => ({ id: stringValue(row, "id"), prospectId: typeof row.prospect_id === "string" ? row.prospect_id : undefined, firstName: stringValue(row, "first_name"), lastName: stringValue(row, "last_name"), company: stringValue(row, "company"), email: stringValue(row, "email"), phone: stringValue(row, "phone"), startedAt: stringValue(row, "started_at"), status: row.status as Client["status"], offer: "FeaseWeb — 49 €/mois", accessStatus: (row.access_status as Client["accessStatus"]) || (row.user_id ? "actif" : "non_invite"), invitedAt: typeof row.invited_at === "string" ? row.invited_at : undefined, activatedAt: typeof row.activated_at === "string" ? row.activated_at : undefined, notes: notesFor(rows.internalNotes ?? [], "client_id", stringValue(row, "id")) }));
  const sites: Site[] = (rows.sites ?? []).map((row) => ({ id: stringValue(row, "id"), clientId: stringValue(row, "client_id"), name: stringValue(row, "name"), slug: stringValue(row, "slug"), previewUrl: stringValue(row, "preview_url"), finalDomain: stringValue(row, "domain"), repository: stringValue(row, "repository"), host: stringValue(row, "hosting_provider"), createdAt: stringValue(row, "created_at"), publishedAt: typeof row.launched_at === "string" ? row.launched_at : undefined, status: row.status as Site["status"], technicalNotes: "" }));
  const payments: Payment[] = (rows.payments ?? []).map((row) => ({ id: stringValue(row, "id"), clientId: stringValue(row, "client_id"), subscriptionId: typeof row.subscription_id === "string" ? row.subscription_id : undefined, amountCents: Number(row.amount_cents ?? 0), paidAt: typeof row.created_at === "string" ? row.created_at : undefined, status: row.status as Payment["status"], invoice: stringValue(row, "invoice_reference"), period: `${stringValue(row, "period_start")} → ${stringValue(row, "period_end")}`, provider: row.provider === "stripe" ? "stripe" : "none", externalReference: typeof row.external_reference === "string" ? row.external_reference : undefined }));
  const latestPaymentStatusForClient = (clientId: string): Payment["status"] | "aucun" => {
    const clientPayments = payments.filter((payment) => payment.clientId === clientId).sort((a, b) => (b.paidAt ?? "").localeCompare(a.paidAt ?? ""));
    return clientPayments[0]?.status ?? "aucun";
  };
  const subscriptions: Subscription[] = (rows.subscriptions ?? []).map((row) => ({ id: stringValue(row, "id"), clientId: stringValue(row, "client_id"), status: row.status as Subscription["status"], amountCents: Number(row.amount_cents ?? 4900), startedAt: typeof row.started_at === "string" ? row.started_at : undefined, nextDueAt: typeof row.next_billing_at === "string" ? row.next_billing_at : undefined, provider: row.provider === "stripe" ? "stripe" : "none", externalCustomerId: typeof row.external_customer_id === "string" ? row.external_customer_id : undefined, externalSubscriptionId: typeof row.external_subscription_id === "string" ? row.external_subscription_id : undefined, externalPriceId: typeof row.external_price_id === "string" ? row.external_price_id : undefined, cancelAtPeriodEnd: booleanValue(row, "cancel_at_period_end"), canceledAt: typeof row.canceled_at === "string" ? row.canceled_at : undefined, lastPaymentStatus: latestPaymentStatusForClient(stringValue(row, "client_id")) }));
  const requests: ModificationRequest[] = (rows.requests ?? []).map((row) => ({ id: stringValue(row, "id"), clientId: stringValue(row, "client_id"), siteId: stringValue(row, "site_id"), createdAt: stringValue(row, "created_at"), title: stringValue(row, "title") || stringValue(row, "category"), category: stringValue(row, "category"), message: stringValue(row, "message"), attachments: Array.isArray(row.attachments) ? row.attachments as string[] : [], priority: row.priority as ModificationRequest["priority"], status: row.status as ModificationRequest["status"], internalReply: stringValue(row, "internal_reply"), resolvedAt: typeof row.resolved_at === "string" ? row.resolved_at : undefined }));
  const clientUpdates: ClientUpdate[] = (rows.clientUpdates ?? []).map((row) => ({ id: stringValue(row, "id"), clientId: stringValue(row, "client_id"), siteId: typeof row.site_id === "string" ? row.site_id : undefined, category: row.category as ClientUpdate["category"], title: stringValue(row, "title"), description: stringValue(row, "description"), status: row.status as ClientUpdate["status"], visibleToClient: booleanValue(row, "visible_to_client"), activityDate: stringValue(row, "activity_date"), createdAt: stringValue(row, "created_at"), updatedAt: stringValue(row, "updated_at") }));
  const seoActions: SeoAction[] = (rows.seoActions ?? []).map((row) => ({ id: stringValue(row, "id"), siteId: stringValue(row, "site_id"), date: stringValue(row, "date"), action: stringValue(row, "action"), description: stringValue(row, "description"), status: row.status as SeoAction["status"] }));
  const seoMetrics: SeoMetric[] = (rows.seoMetrics ?? []).map((row) => ({ id: stringValue(row, "id"), siteId: stringValue(row, "site_id"), clicks: Number(row.clicks ?? 0), impressions: Number(row.impressions ?? 0), ctr: Number(row.ctr ?? 0), averagePosition: Number(row.average_position ?? 0), syncedAt: typeof row.synced_at === "string" ? row.synced_at : undefined }));
  const domains: Domain[] = (rows.domains ?? []).map((row) => ({ id: stringValue(row, "id"), clientId: stringValue(row, "client_id"), name: stringValue(row, "domain"), registrar: stringValue(row, "registrar"), owner: stringValue(row, "owner"), expiresAt: typeof row.expiration_date === "string" ? row.expiration_date : undefined, renewal: row.renewal as Domain["renewal"], dnsStatus: row.dns_status as Domain["dnsStatus"], ssl: row.ssl_status as Domain["ssl"], notes: stringValue(row, "notes") }));
  clients = clients.map((client) => ({ ...client, siteId: sites.find((site) => site.clientId === client.id)?.id, subscriptionId: typeof (rows.subscriptions ?? []).find((row) => row.client_id === client.id)?.id === "string" ? (rows.subscriptions ?? []).find((row) => row.client_id === client.id)?.id as string : undefined, domainId: domains.find((domain) => domain.clientId === client.id)?.id }));
  const activity: ActivityLog[] = (rows.activity ?? []).map((row) => ({ id: stringValue(row, "id"), occurredAt: stringValue(row, "occurred_at"), actor: "admin", entityType: stringValue(row, "entity_type"), entityId: stringValue(row, "entity_id"), message: stringValue(row, "message") }));
  return { prospects, clients, sites, subscriptions, payments, requests, clientUpdates, seoActions, seoMetrics, domains, activity };
}
