/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import { requireClientSpace } from "@/lib/authz";
import { createClient } from "@/lib/supabase/server";
import { LogoutButton } from "@/components/layout/LogoutButton";
import { StartSubscriptionButton, ManageSubscriptionButton } from "@/components/billing/BillingActions";
import { ClientRequestForm } from "@/components/client/ClientRequestForm";
import { ProspectProjectDashboard } from "@/components/client/ProspectProjectDashboard";
import { mapProjectIntake, onboardingProjectSelect } from "@/lib/onboarding";

export const metadata: Metadata = { title: "Espace client — FeaseWeb", description: "Suivez le travail réalisé par FeaseWeb sur votre site.", alternates: { canonical: "/espace-client" }, robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";

const statusLabels: Record<string, string> = { a_preparer: "À préparer", en_creation: "En création", preview: "En attente de validation", corrections: "Corrections en cours", valide: "Validé", mise_en_ligne: "Mise en ligne", actif: "En ligne", suspendu: "Maintenance", archive: "Archivé", incomplet: "En attente de paiement", retard: "Paiement en retard", impaye: "Impayé", annule: "Annulé" };
const updateLabels: Record<string, string> = { seo: "SEO", contenu: "Contenu", maintenance: "Maintenance", site: "Site", securite: "Sécurité", autre: "Autre" };
const formatDate = (value: string | null | undefined) => value ? new Date(value).toLocaleDateString("fr-FR", { day: "numeric", month: "long", year: "numeric" }) : "—";
const formatMonthDay = (value: string) => new Date(value).toLocaleDateString("fr-FR", { weekday: "long", day: "numeric", month: "long" });

export default async function EspaceClientPage({ searchParams }: { searchParams: Promise<{ checkout?: string }> }) {
  const { checkout } = await searchParams;
  const current = await requireClientSpace();
  const supabase = await createClient();
  const { data: intake } = supabase ? await supabase.from("project_intakes").select(onboardingProjectSelect).eq("user_id", current.user.id).maybeSingle() : { data: null };
  if (current.role === "prospect" && intake) return <ProspectProjectDashboard project={mapProjectIntake(intake)} checkout={checkout} />;
  const { data: client } = supabase ? await supabase.from("clients").select("id, company, first_name, status").eq("user_id", current.user.id).maybeSingle() : { data: null };
  const { data: site } = client && supabase ? await supabase.from("sites").select("id, name, domain, production_url, status").eq("client_id", client.id).order("created_at").limit(1).maybeSingle() : { data: null };
  const { data: subscription } = client && supabase ? await supabase.from("subscriptions").select("status, next_billing_at, cancel_at_period_end").eq("client_id", client.id).maybeSingle() : { data: null };
  const { data: payments } = client && supabase ? await supabase.from("payments").select("id, amount_cents, status, created_at, invoice_reference").eq("client_id", client.id).order("created_at", { ascending: false }).limit(10) : { data: [] };
  const { data: updates } = client && supabase ? await supabase.from("client_updates").select("id, category, title, description, status, activity_date, created_at").eq("client_id", client.id).eq("visible_to_client", true).order("activity_date", { ascending: false }).order("created_at", { ascending: false }) : { data: [] };
  const { data: requests } = client && supabase ? await supabase.from("modification_requests").select("id, title, category, message, status, created_at, resolved_at").eq("client_id", client.id).order("created_at", { ascending: false }) : { data: [] };
  const firstName = client?.first_name || current.profile?.first_name || "";
  return <main className="client-space"><header className="client-header"><div><p className="client-eyebrow">ESPACE CLIENT FEASEWEB</p><h1>Bonjour{firstName ? ` ${firstName}` : ""}.</h1><p>FeaseWeb travaille régulièrement sur votre site et vous permet de suivre ce qui est fait.</p></div><LogoutButton /></header>
    {checkout === "success" && <div className="client-alert">Votre demande d'abonnement a bien été reçue. Le statut se met à jour après confirmation de Stripe.</div>}
    {checkout === "cancelled" && <div className="client-alert muted">Le paiement a été annulé. Vous pouvez reprendre lorsque vous serez prêt.</div>}
    {client ? <>
      <section className="client-hero-card"><div><p className="client-eyebrow">VOTRE SITE</p><h2>{client.company}</h2><p>{site?.domain || site?.production_url || "Domaine non renseigné"}</p></div><div className="client-status-block"><span>État du site</span><strong>{site ? statusLabels[site.status] ?? site.status : "Non renseigné"}</strong></div>{site?.production_url && <a className="client-button secondary" href={site.production_url} target="_blank" rel="noreferrer">Voir mon site ↗</a>}</section>
      <div className="client-dashboard-grid"><section className="client-card client-activity-card"><div className="client-card-heading"><div><p className="client-eyebrow">SUIVI DU SERVICE</p><h2>Activité FeaseWeb</h2></div></div>{updates?.length ? <div className="client-update-list">{updates.map((update) => <article className="client-update" key={update.id}><div className="client-update-date">{formatMonthDay(update.activity_date)}</div><div className="client-update-mark" /><div><p className="client-update-category">{updateLabels[update.category] ?? update.category}</p><h3>{update.title}</h3><p>{update.description}</p><span className={`client-chip ${update.status}`}>{update.status === "termine" ? "Terminé" : update.status === "en_cours" ? "En cours" : "Prévu"}</span></div></article>)}</div> : <div className="client-empty"><h3>Le suivi de votre site apparaîtra ici</h3><p>FeaseWeb ajoutera les interventions au fur et à mesure du travail réalisé.</p></div>}</section>
        <section className="client-card"><div className="client-card-heading"><div><p className="client-eyebrow">PROCHAINES ÉTAPES</p><h2>À venir</h2></div></div>{updates?.filter((update) => update.status !== "termine").length ? updates.filter((update) => update.status !== "termine").map((update) => <div className="client-next-item" key={update.id}><span>{updateLabels[update.category] ?? update.category}</span><strong>{update.title}</strong><small>{update.status === "en_cours" ? "En cours" : "Prévu"}</small></div>) : <div className="client-empty compact"><p>Aucune action à venir affichée pour le moment.</p></div>}</section>
        <section className="client-card"><div className="client-card-heading"><div><p className="client-eyebrow">SERVICES</p><h2>État du service</h2></div></div><div className="client-service-list"><div><span>Site internet</span><strong>{site ? statusLabels[site.status] ?? site.status : "Non renseigné"}</strong></div><div><span>Abonnement</span><strong>{subscription ? statusLabels[subscription.status] ?? subscription.status : "Non renseigné"}</strong></div><div><span>Hébergement, maintenance et SEO</span><strong>Non renseigné</strong></div></div></section>
      </div>
      <section className="client-card client-requests"><div className="client-card-heading"><div><p className="client-eyebrow">BESOIN D'UNE MODIFICATION ?</p><h2>Vos demandes</h2></div></div><div className="client-request-layout"><div>{requests?.length ? requests.map((request) => <article className="client-request-row" key={request.id}><div><strong>{request.title || request.category}</strong><p>{request.message}</p></div><span className={`client-chip ${request.status}`}>{request.status === "recue" ? "Reçue" : request.status === "en_cours" ? "En cours" : request.status === "terminee" ? "Terminée" : "À préciser"}</span></article>) : <div className="client-empty compact"><p>Aucune demande pour le moment. Vous pouvez nous écrire ci-contre.</p></div>}</div><ClientRequestForm /></div></section>
      <section className="client-card client-subscription"><div><p className="client-eyebrow">ABONNEMENT</p><h2>Mon abonnement</h2><p className="client-price">49 €<span>/mois</span></p><p>{subscription ? statusLabels[subscription.status] ?? subscription.status : "Aucun abonnement actif"}{subscription?.next_billing_at ? ` · prochaine échéance ${formatDate(subscription.next_billing_at)}` : ""}</p></div><div>{subscription ? <ManageSubscriptionButton /> : <StartSubscriptionButton />}<p className="client-footnote">Les paiements et factures sont gérés de manière sécurisée par Stripe.</p></div></section>
      {payments && payments.length > 0 && <section className="client-card"><div className="client-card-heading"><div><p className="client-eyebrow">FACTURES</p><h2>Historique des paiements</h2></div></div><div className="client-payments">{payments.map((payment) => <div key={payment.id}><span>{formatDate(payment.created_at)}</span><strong>{(payment.amount_cents / 100).toFixed(2)} €</strong><small>{payment.status} {payment.invoice_reference ? `· ${payment.invoice_reference}` : ""}</small></div>)}</div></section>}
    </> : <section className="client-card client-empty"><h2>Votre espace est prêt.</h2><p>Aucun site n'est encore associé à ce compte.</p></section>}
    <footer className="client-support"><div><p className="client-eyebrow">BESOIN DE NOUS ?</p><h2>Une question ou une modification à prévoir ?</h2><p>Utilisez vos demandes ci-dessus : l'équipe FeaseWeb suivra votre message depuis le même dossier.</p></div></footer>
  </main>;
}
