"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";

function maskEmail(email: string) { const [local, domain] = email.split("@"); if (!local || !domain) return email; return `${local.slice(0, 1)}***@${domain}`; }

function ConfirmationPanel({ initialEmail = "", invalid = false, onOtherEmail }: { initialEmail?: string; invalid?: boolean; onOtherEmail: () => void }) {
  const [email, setEmail] = useState(initialEmail); const [loading, setLoading] = useState(false); const [sent, setSent] = useState(false); const [cooldown, setCooldown] = useState(0); const [error, setError] = useState("");
  async function resend() { setLoading(true); setError(""); const response = await fetch("/api/onboarding/confirmation/resend", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); const body = await response.json().catch(() => null); setLoading(false); if (!response.ok) { setError(body?.error ?? "Saisissez une adresse email valide."); return; } setSent(true); setCooldown(60); const timer = window.setInterval(() => setCooldown((value) => { if (value <= 1) { window.clearInterval(timer); return 0; } return value - 1; }), 1000); }
  return <div className="rounded-sm border border-line bg-bg-alt p-6" role="status">{invalid && <p className="rounded-sm bg-amber-50 p-3 text-sm text-amber-800">Ce lien est invalide ou a expiré. Demandez un nouveau lien pour continuer.</p>}<h2 className="mt-4 font-serif text-2xl text-ink">Confirmez votre adresse email</h2><p className="mt-3 text-sm leading-6 text-ink-soft">Nous venons de vous envoyer un email. Cliquez sur le lien qu’il contient pour continuer la configuration de votre site.</p>{initialEmail && <p className="mt-3 text-sm font-medium text-ink">Email envoyé à {maskEmail(initialEmail)}</p>}<div className="mt-6 space-y-3"><label className="block text-sm font-medium text-ink" htmlFor="confirmation-email">Vous n’avez rien reçu ?<input id="confirmation-email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="vous@entreprise.fr" className="mt-1.5 w-full rounded-sm border border-line bg-white px-3 py-2.5" /></label><button type="button" onClick={() => void resend()} disabled={loading || cooldown > 0 || !email} className="w-full rounded-sm border border-brand px-5 py-3 text-sm font-medium text-brand disabled:opacity-50">{loading ? "Demande en cours…" : cooldown ? `Nouvel envoi possible dans ${cooldown}s` : "Renvoyer l’email"}</button>{sent && <p className="text-sm text-brand">Si cette adresse correspond à un compte en attente, un nouvel email a été demandé.</p>}{error && <p className="text-sm text-red-700" role="alert">{error}</p>}</div><button type="button" onClick={onOtherEmail} className="mt-6 text-sm text-brand underline underline-offset-4">Utiliser une autre adresse email</button></div>;
}

export function AccountCreationForm({ initialError = "" }: { initialError?: string }) {
  const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [confirmation, setConfirmation] = useState(false); const [confirmationEmail, setConfirmationEmail] = useState(""); const [recovery, setRecovery] = useState(Boolean(initialError));
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setError("");
    const form = new FormData(event.currentTarget);
    const response = await fetch("/api/onboarding/account", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) });
    const body = await response.json().catch(() => null); setLoading(false);
    if (!response.ok) { setError(body?.error ?? "Impossible de créer votre espace."); return; }
    if (body?.needsConfirmation) { setConfirmationEmail(String(form.get("email") ?? "")); setConfirmation(true); return; }
    window.location.assign(body?.redirect ?? "/creer-mon-site");
  }
  if (confirmation || recovery) return <ConfirmationPanel initialEmail={confirmationEmail} invalid={recovery} onOtherEmail={() => { setConfirmation(false); setRecovery(false); setError(""); }} />;
  const field = (id: string, label: string, type = "text", required = true) => <label className="block text-sm font-medium text-ink" htmlFor={id}>{label}<input id={id} name={id} type={type} required={required} className="mt-1.5 w-full rounded-sm border border-line bg-white px-3 py-2.5" /></label>;
  return <form onSubmit={submit} className="space-y-5 rounded-sm border border-line bg-white p-6 shadow-sm">{error && <p role="alert" className="rounded-sm bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="grid gap-5 sm:grid-cols-2">{field("firstName", "Prénom")}{field("lastName", "Nom")}</div>{field("company", "Entreprise")}{field("email", "Email", "email")}{field("phone", "Téléphone", "tel", false)}<div className="grid gap-5 sm:grid-cols-2">{field("password", "Mot de passe", "password")}{field("confirmation", "Confirmation", "password")}</div><label className="flex gap-3 text-sm text-ink-soft"><input name="privacyConsent" type="checkbox" value="true" required className="mt-1" /> <span>J’accepte que FeaseWeb utilise ces informations pour préparer mon projet et me contacter.</span></label><button className="w-full rounded-sm bg-brand px-5 py-3 font-medium text-white hover:bg-brand-dark disabled:opacity-60" disabled={loading}>{loading ? "Création…" : "Créer mon espace"}</button><p className="text-center text-sm text-ink-soft">Vous avez déjà un espace ? <Link className="font-medium text-brand underline" href="/connexion">Se connecter</Link></p></form>;
}
