"use client";

import { useEffect, useRef, useState } from "react";
import type { OnboardingProject } from "@/lib/onboarding";
import { toOnboardingPatch } from "@/lib/onboarding";
import { trackEvent } from "@/lib/analytics";

type Project = OnboardingProject;
const TOTAL_STEPS = 7;
const activities = [["artisan_btp", "Artisan / BTP"], ["commerce", "Commerce"], ["restaurant", "Restaurant / Alimentation"], ["beaute", "Beauté / Bien-être"], ["sante", "Santé"], ["immobilier", "Immobilier"], ["automobile", "Automobile"], ["services_entreprises", "Services aux entreprises"], ["profession_liberale", "Profession libérale"], ["autre", "Autre"]] as const;
const objectives = [["devis", "Recevoir des demandes de devis"], ["appels", "Recevoir des appels"], ["presentation", "Présenter mon entreprise"], ["rendez_vous", "Prendre des rendez-vous"], ["vente", "Vendre des produits"], ["visite", "Faire venir des clients"]] as const;
const pages = [["accueil", "Accueil"], ["services", "Services"], ["realisations", "Réalisations"], ["a_propos", "À propos"], ["avis", "Éléments de confiance"], ["tarifs", "Tarifs"], ["contact", "Contact"], ["rendez_vous", "Prise de rendez-vous"]] as const;
const styles = [["elegant_premium", "01 — Classique professionnel", "model-classic"], ["moderne_epure", "02 — Moderne", "model-modern"], ["artisan_rassurant", "03 — Premium", "model-premium"], ["dynamique_commercial", "04 — Local / artisan", "model-local"], ["sobre_professionnel", "05 — Minimal", "model-minimal"], ["chaleureux_humain", "06 — Impact", "model-impact"]] as const;
const accessLabels: Record<string, string> = { refonte_complete: "Refaire complètement mon site", modernisation: "Moderniser mon site actuel", conseil: "FeaseWeb vous conseillera" };
const labels: Record<string, string> = Object.fromEntries([...activities, ...objectives, ...pages, ...styles].map(([key, label]) => [key, label]));

function MiniPreview({ item, selected, onClick }: { item: typeof styles[number]; selected: boolean; onClick: () => void }) {
  const [key, label, variant] = item;
  return <button type="button" onClick={onClick} aria-pressed={selected} className={`site-model-choice ${selected ? "selected" : ""}`}>
    <span className={`site-model-preview ${variant}`} aria-hidden="true">
      <span className="site-model-header"><strong>Atelier</strong><span className="site-model-nav"><i>Accueil</i><i>Services</i><i>Contact</i></span><b>Devis</b></span>
      <span className="site-model-hero"><span><small>VOTRE ACTIVITÉ</small><strong>Un site qui vous ressemble.</strong><em>Nous contacter</em></span><span className="site-model-photo"><i>Photo</i></span></span>
      <span className="site-model-services"><i>Service 01</i><i>Service 02</i><i>Service 03</i></span>
      <span className="site-model-proof"><b>Votre savoir-faire</b><i>Une présence claire et rassurante</i></span>
      <span className="site-model-final-cta">Parlons de votre projet <b>→</b></span>
      <span className="site-model-footer">Atelier · Mentions légales · Contact</span>
    </span>
    <span className="site-model-label">{label}</span>
    {selected && <span className="site-model-selected">Modèle sélectionné ✓</span>}
    <span className="sr-only">Modèle {key}</span>
  </button>;
}

export function OnboardingConfigurator({ initial }: { initial: Project }) {
  const [project, setProject] = useState<Project>({ ...initial, requestedPages: initial.requestedPages.length ? initial.requestedPages : ["accueil", "contact"], availableAssets: initial.availableAssets });
  const [step, setStep] = useState(Math.min(Math.max(Number(initial.currentStep ?? 1), 1), TOTAL_STEPS));
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const [done, setDone] = useState(false);
  const startedEventId = useRef<string | null>(null);

  useEffect(() => { const id = typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : "session"; startedEventId.current = `configurator_started:${id}`; trackEvent("configurator_started", startedEventId.current); }, []);
  async function save(changes: Project, nextStep = step) { setSaving(true); setError(""); const response = await fetch("/api/onboarding/project", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(toOnboardingPatch(changes, nextStep)) }); const body = await response.json().catch(() => null); setSaving(false); if (!response.ok) { setError(body?.error ?? "Impossible d'enregistrer votre projet."); return false; } if (body?.trackingEventId) trackEvent("configurator_completed", body.trackingEventId); setProject(body.project); return true; }
  async function advance() { const next = Math.min(step + 1, TOTAL_STEPS); if (await save(project, next)) setStep(next); }
  const choose = <K extends keyof Project>(key: K, value: Project[K]) => setProject((old) => ({ ...old, [key]: value }));
  const multi = (key: "requestedPages" | "primaryObjectives" | "availableAssets", value: string, exclusive = false) => setProject((old) => { const current = old[key] ?? []; if (exclusive) return { ...old, [key]: [value] }; const next = current.includes(value) ? current.filter((item) => item !== value) : [...current.filter((item) => item !== "aucun"), value]; return { ...old, [key]: next }; });
  const header = (title: string, intro: string) => <><p className="text-xs font-medium uppercase tracking-widest text-brand-dark">Étape {step} / {TOTAL_STEPS}</p><h1 className="mt-3 font-serif text-3xl text-ink md:text-4xl">{title}</h1><p className="mt-3 text-ink-soft">{intro}</p></>;
  const optionGrid = (items: readonly (readonly string[])[], key: "activity" | "primaryObjective" | "contactChannel" | "contactSlot") => <div className="mt-8 grid gap-3 sm:grid-cols-2">{items.map(([value, label]) => { const selected = project[key] === value; return <button type="button" key={value} onClick={() => choose(key, value)} aria-pressed={selected} className={`rounded-sm border p-4 text-left transition ${selected ? "border-brand bg-brand/5 ring-1 ring-brand" : "border-line bg-white hover:border-brand"}`}><span className="font-medium text-ink">{label}</span></button>; })}</div>;
  if (done) return <div className="rounded-sm border border-line bg-white p-8 text-center"><p className="text-xs font-medium uppercase tracking-widest text-brand-dark">Projet enregistré</p><h2 className="mt-3 font-serif text-3xl text-ink">Votre projet FeaseWeb est configuré.</h2><p className="mt-3 text-ink-soft">Vous pouvez maintenant consulter l’offre et démarrer votre projet depuis votre espace.</p><a href="/espace-client" className="mt-6 inline-flex rounded-sm bg-brand px-5 py-3 font-medium text-white">Accéder à mon espace</a></div>;
  let body: React.ReactNode;
  if (step === 1) body = <>{header("Quelle est votre activité ?", "Quelques choix suffisent pour orienter votre projet.")}{optionGrid(activities, "activity")}</>;
  if (step === 2) body = <>{header("Avez-vous déjà un site internet ?", "Nous adapterons la préparation à votre situation.")}<div className="mt-8 grid gap-3 sm:grid-cols-2">{[[false, "Non"], [true, "Oui"]].map(([value, label]) => <button type="button" key={String(value)} onClick={() => choose("hasExistingSite", value as boolean)} aria-pressed={project.hasExistingSite === value} className={`rounded-sm border p-4 text-left transition ${project.hasExistingSite === value ? "border-brand bg-brand/5 ring-1 ring-brand" : "border-line bg-white hover:border-brand"}`}><span className="font-medium text-ink">{label}</span></button>)}</div>{project.hasExistingSite && <div className="mt-6 space-y-5 rounded-sm bg-bg-alt p-5"><label className="block text-sm font-medium">Adresse de votre site actuel<input value={project.existingSiteUrl ?? ""} onChange={(e) => choose("existingSiteUrl", e.target.value)} type="url" className="mt-1.5 w-full rounded-sm border border-line px-3 py-2.5" placeholder="https://" required /></label><div><p className="text-sm font-medium">Que souhaitez-vous faire ?</p><div className="mt-3 grid gap-3">{[["refonte_complete", "Refaire complètement mon site", "Repartir sur un nouveau site plus moderne."], ["modernisation", "Moderniser mon site actuel", "Conserver l’essentiel en améliorant le design et l’efficacité."], ["conseil", "Je ne sais pas", "FeaseWeb vous conseillera sur la meilleure solution."]].map(([value, label, description]) => <button type="button" key={value} onClick={() => choose("existingSiteProject", value)} aria-pressed={project.existingSiteProject === value} className={`rounded-sm border p-4 text-left ${project.existingSiteProject === value ? "border-brand bg-white ring-1 ring-brand" : "border-line bg-white"}`}><strong>{label}</strong><span className="mt-1 block text-sm text-ink-soft">{description}</span></button>)}</div></div></div>}</>;
  if (step === 3) body = <>{header("Quels sont vos objectifs ?", "Vous pouvez sélectionner plusieurs réponses.")}<div className="mt-8 grid gap-3 sm:grid-cols-2">{objectives.map(([value, label]) => { const selected = (project.primaryObjectives?.length ? project.primaryObjectives : project.primaryObjective ? [project.primaryObjective] : []).includes(value); return <button type="button" key={value} onClick={() => multi("primaryObjectives", value)} aria-pressed={selected} className={`rounded-sm border p-4 text-left transition ${selected ? "border-brand bg-brand/5 ring-1 ring-brand" : "border-line bg-white hover:border-brand"}`}>{selected ? "✓ " : ""}<span className="font-medium text-ink">{label}</span></button>; })}</div></>;
  if (step === 4) body = <>{header("Que souhaitez-vous présenter ?", "Sélectionnez les pages utiles à votre futur site.")}<div className="mt-8 grid gap-3 sm:grid-cols-2">{pages.map(([value, label]) => <button type="button" key={value} onClick={() => multi("requestedPages", value)} aria-pressed={project.requestedPages.includes(value)} className={`rounded-sm border p-4 text-left ${project.requestedPages.includes(value) ? "border-brand bg-brand/5 ring-1 ring-brand" : "border-line bg-white"}`}>{project.requestedPages.includes(value) ? "✓ " : ""}{label}</button>)}</div></>;
  if (step === 5) body = <>{header("Quel style vous ressemble le plus ?", "Choisissez la direction visuelle qui vous parle le plus. FeaseWeb adaptera ensuite le site à votre activité.")}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{styles.map((item) => <MiniPreview item={item} selected={project.styleDirection === item[0]} onClick={() => choose("styleDirection", item[0])} key={item[0]} />)}</div></>;
  if (step === 6) body = <>{header("Qu’avez-vous déjà ?", "Ces éléments nous indiquent comment préparer votre projet.")}<div className="mt-8 grid gap-3 sm:grid-cols-2">{[["logo", "Logo"], ["photos", "Photos"], ["textes", "Textes"], ["avis", "Retours clients"], ["aucun", "Aucun de ces éléments"]].map(([value, label]) => <button type="button" key={value} onClick={() => multi("availableAssets", value, value === "aucun")} aria-pressed={project.availableAssets.includes(value)} className={`rounded-sm border p-4 text-left ${project.availableAssets.includes(value) ? "border-brand bg-brand/5 ring-1 ring-brand" : "border-line bg-white"}`}>{project.availableAssets.includes(value) ? "✓ " : ""}{label}</button>)}</div></>;
  if (step === 7) body = <>{header("Comment préférez-vous que nous échangions ?", "Une dernière indication pour faciliter les premiers échanges.")}<p className="mt-8 text-sm font-medium">Canal préféré</p>{optionGrid([["telephone", "Téléphone"], ["whatsapp", "WhatsApp"], ["email", "Email"]], "contactChannel")}<div className="mt-10 rounded-sm border border-line bg-bg-alt p-5"><h2 className="font-serif text-2xl">Votre projet en un coup d’œil</h2><p className="mt-3 text-sm text-ink-soft">{labels[project.activity ?? ""] ?? "Activité à choisir"} · {project.hasExistingSite ? accessLabels[project.existingSiteProject ?? ""] ?? "Site existant" : "Nouveau site"} · {labels[project.styleDirection ?? ""] ?? "Style à choisir"}</p></div></>;
  const canContinue = step === 1 ? !!project.activity : step === 2 ? (!project.hasExistingSite || (!!project.existingSiteUrl && !!project.existingSiteProject)) : step === 3 ? (project.primaryObjectives?.length ?? (project.primaryObjective ? 1 : 0)) > 0 : step === 4 ? project.requestedPages.length > 0 : step === 5 ? !!project.styleDirection : step === 6 ? project.availableAssets.length > 0 : !!project.contactChannel;
  return <section className="onboarding-shell">{error && <p className="mb-5 rounded-sm bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>}<div className="onboarding-question">{body}</div><div className="mt-10 flex justify-between gap-3">{step > 1 ? <button type="button" className="rounded-sm border border-line px-5 py-3 text-sm" onClick={() => setStep(step - 1)}>Retour</button> : <span />}{step < TOTAL_STEPS ? <span className={!canContinue ? "pointer-events-none opacity-50" : ""}><button type="button" disabled={saving} onClick={() => void advance()} className="rounded-sm bg-brand px-5 py-3 font-medium text-white disabled:opacity-60">{saving ? "Enregistrement…" : "Continuer"}</button></span> : <button type="button" disabled={!canContinue || saving} onClick={async () => { if (await save(project, TOTAL_STEPS)) setDone(true); }} className="rounded-sm bg-brand px-5 py-3 font-medium text-white disabled:opacity-50">{saving ? "Enregistrement…" : "Valider mon projet"}</button>}</div></section>;
}
