"use client";

import Link from "next/link";
import { useState } from "react";
import { formatDate, getClientName, labelMap } from "@/lib/backoffice";
import { getClientCompleteness, getClientProject, getProjectStatusLabel, getProspectBusinessState, type ProspectBusinessFilter } from "@/lib/admin-presentation";
import { useBackoffice } from "@/lib/backoffice-store";
import { EmptyState, PageHeading, StatusBadge } from "@/components/admin/AdminApp";

const prospectFilters: Array<[ProspectBusinessFilter, string]> = [["all", "Tous"], ["to_call", "À appeler"], ["appointments", "RDV prévus"], ["to_validate", "À valider"], ["approved", "Validés"], ["to_complete", "À compléter"], ["declined", "Refusés"]];

export function ProspectsPage() {
  const { data } = useBackoffice();
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState<ProspectBusinessFilter>("all");
  const rows = data.prospects.map((prospect) => ({ prospect, state: getProspectBusinessState(prospect, data.projectIntakes.find((project) => project.prospectId === prospect.id)) })).filter(({ prospect, state }) => {
    const haystack = `${prospect.company} ${prospect.email} ${prospect.firstName} ${prospect.lastName}`.toLowerCase();
    return (!query || haystack.includes(query.toLowerCase())) && (filter === "all" || state.filter === filter);
  });
  return <><PageHeading eyebrow="Prospects" title="Les prochains échanges, clairement." description="Chaque dossier affiche son état métier et la prochaine action utile." /><div className="admin-toolbar"><input aria-label="Rechercher un prospect" placeholder="Entreprise, nom ou email" value={query} onChange={(event) => setQuery(event.target.value)} /><select aria-label="Filtrer les prospects" value={filter} onChange={(event) => setFilter(event.target.value as ProspectBusinessFilter)}>{prospectFilters.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div><div className="admin-filter-pills">{prospectFilters.map(([value, label]) => <button type="button" className={filter === value ? "active" : ""} onClick={() => setFilter(value)} key={value}>{label}</button>)}</div><div className="admin-table-wrap admin-responsive-list">{rows.length ? <table className="admin-table"><thead><tr><th>Prospect</th><th>Entreprise</th><th>État actuel</th><th>Prochaine action</th><th>Rendez-vous</th><th /></tr></thead><tbody>{rows.map(({ prospect, state }) => <tr key={prospect.id}><td><Link href={`/admin/prospects/${prospect.id}`} className="admin-table-link">{prospect.firstName} {prospect.lastName}</Link><small>{prospect.email}</small></td><td><strong>{prospect.company}</strong><small>{prospect.phone || "Téléphone non renseigné"}</small></td><td><StatusBadge value={state.filter === "declined" ? "declined" : state.filter === "to_validate" ? "pending" : "neutral"} /><small>{state.label}</small></td><td>{state.nextAction}</td><td>{prospect.review?.appointmentDate ? `${prospect.review.appointmentDate} ${prospect.review.appointmentTime ?? ""}` : "—"}</td><td><Link href={`/admin/prospects/${prospect.id}`} className="admin-text-button">Ouvrir →</Link></td></tr>)}</tbody></table> : <EmptyState title="Aucun prospect" detail="Les dossiers correspondant à ce filtre apparaîtront ici." />}</div></>;
}

export function ClientsPage() {
  const { data, setClientStatus } = useBackoffice();
  const [query, setQuery] = useState("");
  const rows = data.clients.filter((client) => `${client.company} ${client.email} ${client.firstName} ${client.lastName}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeading eyebrow="Clients" title="Les sites en cours de suivi." description="Un accès rapide à l'état du site, aux demandes et aux mises à jour de chaque client." /><div className="admin-toolbar"><input aria-label="Rechercher un client" placeholder="Entreprise, nom ou email" value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="admin-table-wrap admin-responsive-list">{rows.length ? <table className="admin-table"><thead><tr><th>Client / entreprise</th><th>État du site</th><th>Complétude</th><th>Dernière activité</th><th>Action</th></tr></thead><tbody>{rows.map((client) => { const project = getClientProject(client, data.projectIntakes); const site = data.sites.find((item) => item.id === client.siteId); const latest = data.activity.filter((event) => event.entityId === client.id || event.entityId === site?.id).sort((a, b) => b.occurredAt.localeCompare(a.occurredAt))[0]; return <tr key={client.id}><td><Link href={`/admin/clients/${client.id}`} className="admin-table-link">{getClientName(client)}</Link><small>{client.company} · {client.email}</small></td><td><StatusBadge value={project?.status ?? site?.status ?? "neutral"} /><small>{getProjectStatusLabel(project?.status)}</small></td><td>{getClientCompleteness(project)}</td><td>{latest ? <><strong>{latest.message}</strong><small>{formatDate(latest.occurredAt)}</small></> : "Aucune activité"}</td><td><select className="admin-inline-select" value={client.status} onChange={(event) => void setClientStatus(client.id, event.target.value as never)} aria-label={`Statut de ${client.company}`}><option value="actif">Actif</option><option value="en_attente">En attente</option><option value="suspendu">Suspendu</option><option value="resilie">Résilié</option></select><Link href={`/admin/clients/${client.id}`} className="admin-text-button">Ouvrir →</Link></td></tr>; })}</tbody></table> : <EmptyState title="Aucun client" detail="Les clients apparaîtront ici après confirmation de leur abonnement." />}</div></>;
}

export function SitesPage() {
  const { data, setSiteStatus } = useBackoffice();
  const groups = ["preparation", "building", "preview_ready", "client_feedback", "finalizing", "live"];
  return <><PageHeading eyebrow="Production" title="Les sites à faire avancer." description="Suivez les projets actifs de la préparation à la mise en ligne." /><div className="admin-production-flow">{groups.map((status) => <div key={status}><span>{data.projectIntakes.filter((project) => project.status === status).length}</span><small>{getProjectStatusLabel(status)}</small></div>)}</div><div className="admin-table-wrap admin-responsive-list">{data.sites.length ? <table className="admin-table"><thead><tr><th>Site</th><th>Client</th><th>État du site</th><th>Aperçu</th><th>Action</th></tr></thead><tbody>{data.sites.map((site) => { const client = data.clients.find((item) => item.id === site.clientId); const project = data.projectIntakes.find((item) => item.clientId === site.clientId); return <tr key={site.id}><td><strong>{site.name}</strong><small>/{site.slug}</small></td><td>{client ? <Link href={`/admin/clients/${client.id}`} className="admin-table-link">{client.company}</Link> : "—"}</td><td><StatusBadge value={project?.status ?? site.status} /><small>{project ? getProjectStatusLabel(project.status) : labelMap[site.status]}</small></td><td>{site.previewUrl ? <a href={site.previewUrl} target="_blank" rel="noreferrer" className="admin-text-button">Ouvrir ↗</a> : "Pas encore disponible"}</td><td><select className="admin-inline-select" value={site.status} onChange={(event) => void setSiteStatus(site.id, event.target.value as never)} aria-label={`État du site ${site.name}`}>{["a_preparer", "en_creation", "preview", "corrections", "valide", "mise_en_ligne", "actif", "suspendu", "archive"].map((status) => <option key={status} value={status}>{labelMap[status]}</option>)}</select>{client && <Link href={`/admin/clients/${client.id}`} className="admin-text-button">Dossier →</Link>}</td></tr>; })}</tbody></table> : <EmptyState title="Aucun site" detail="Les sites associés aux clients apparaîtront ici." />}</div></>;
}
